version: "3.8"
services:
  nginx:
    dns:
      - 8.8.8.8
      - 8.8.4.4
    build:
      context: ./docker/images
      dockerfile: nginx.Dockerfile
    working_dir: /var/www/html
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
      - ./docker/logs/nginx_log:/var/log/nginx
      - ./docker/config/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql

  php:
    build:
      context: ./docker/images
      dockerfile: php.Dockerfile
    volumes:
      - .:/var/www/html
      - ./docker/logs/php-fpm/php-fpm.log:/var/log/php-fpm.log
      - ./docker/config/php-fpm/custom.ini:/usr/local/etc/php/conf.d/custom.ini
  mysql:
    build:
      context: ./docker/images
      dockerfile: mysql.Dockerfile
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./docker/data/mysql:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "false"
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "laravel"
  redis:
    image: redis
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 9090:80
    depends_on:
      - mysql
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
